@@ -468,7 +468,7 @@ public boolean dispatchEvent(AWTEvent e) {
                     // in the Window.
                     //
                     // * If we're in SendMessage, then this is a synthetic
-                    //   WINDOW_GAINED_FOCUS message which was generated by a
+                    //   WINDOW_GAINED_FOCUS message which was generated by
                     //   the FOCUS_GAINED handler. Allow the Component to
                     //   which the FOCUS_GAINED message was targeted to
                     //   receive the focus.