@@ -79,6 +79,7 @@ public static void main(String[] args) throws Throwable {
             r.stop();
             r.dump(file);
         }
+        testInputOutput(file);
         testAutogeneratedFilename(file, autogenerated);
 
         testEventInclude(file);
@@ -92,6 +93,17 @@ public static void main(String[] args) throws Throwable {
         testThreadInclude(file);
     }
 
+    private static void testInputOutput(Path file) throws Throwable {
+        List<String> arguments = new ArrayList<>();
+        arguments.add("scrub");
+        arguments.add(file.toAbsolutePath().toString());
+        arguments.add(file.toAbsolutePath().toString());
+
+        OutputAnalyzer oa = ExecuteHelper.jfr(arguments.toArray(String[]::new));
+        oa.shouldContain("output file can't be same as input file");
+        oa.shouldNotHaveExitValue(0);
+    }
+
     private static void testAutogeneratedFilename(Path file, Path autogenerated) throws Throwable {
         List<String> arguments = new ArrayList<>();
         arguments.add("scrub");